export const en = {
	language: 'Language',
	username: 'Username',
	password: 'Password',
	saveLogin: 'Save login',
	continue: 'Continue',
	pleaseInputCodeFirstLogin: 'Please input code for first login',
	inputCode: 'Input code',
	quickReport: 'Quick Report',
	daily: 'Daily',
	all: 'All',
	complete: 'Complete',
	outOfDate: 'Out of date',
	notExpiredYet: 'Not expired yet',
	feedBack: 'Feed back',
	openAgain: 'Open again',
	problem: 'Propblem',
	cancelled: 'Cancelled',
	myTask: 'My task',
	table: 'Table',
	list: 'List',
	task: 'Task',
	delivered: 'Delivered',
	running: 'Running',
	share: 'Share',
	search: 'Search',
	weekly: 'Weekly',
	monthly: 'monthly',
	listDetail: 'List detail',
	creator: 'Creator',
	receiver: 'Receiver',
	status: 'Status',
	createTask: 'Create task',
	seeMore: 'More',
	updateProgress: 'Update progress',
	taskDetails: 'Task Details',
	nomal: 'Nomal',
	workResults: 'Work Results',
	testHeader: 'Test header',
	create: 'Create',
	connectWithTicket: 'Connect with ticket',
	issue: 'Issue',
	attachments: 'Attachments',
	comment: 'Comment',
	result: 'Result',
	generateNewResults: 'Generate new results',
	workTime: 'Work time',
	notification: 'Notification',
	more: 'More',
};
