export const vi = {
	language: 'Ngôn ngữ',
	username: 'Tài khoản',
	password: 'Mật khẩu',
	saveLogin: 'Lưu cho lần đăng nhập sau',
	continue: 'Tiếp tục',
	pleaseInputCodeFirstLogin: 'Vui lòng nhập code khách hàng cho lần đầu đăng nhập',
	inputCode: 'Nhập mã',
	quickReport: 'Báo cáo nhanh',
	daily: 'Hàng ngày',
	all: 'Tất cả',
	complete: 'Hoàn thành',
	outOfDate: 'Quá hạn',
	notExpiredYet: 'Chưa quá hạn',
	feedBack: 'Phản hồi',
	openAgain: 'Mở lại',
	problem: 'sự cố',
	cancelled: 'Đã hủy',
	myTask: 'Task của tôi',
	table: 'Bảng',
	list: 'Danh sách',
	task: 'Nhiệm vụ',
	delivered: 'Đã giao',
	running: 'Đang chạy',
	share: 'Chia sẻ',
	search: 'Tìm kiếm',
	weekly: 'Hàng tuần',
	monthly: 'Hàng tháng',
	listDetail: 'Danh sách chi tiết',
	creator: 'Người tạo',
	receiver: 'Người nhận',
	status: 'Trạng thái',
	createTask: 'Tạo task',
	seeMore: 'xem thêm',
	updateProgress: 'Cập nhật tiến độ',
	taskDetails: 'Chi tiết nhiệm vụ',
	nomal: 'Bình thường',
	workResults: 'Kết quả công việc',
	testHeader: 'Đầu mục kiểm tra',
	create: 'Tạo mới',
	connectWithTicket: 'Kết nối với Ticket',
	issue: 'Vấn đề',
	attachments: 'Tệp đính kèm',
	comment: 'Bình luận',
	result: 'Kết quả',
	generateNewResults: 'Tạo kết quả mới',
	workTime: 'Giờ làm',
	notification: 'Thông báo',
	more: 'Thêm',
};
