export const images = {
	ic_downloading: require('./images/ic_downloading.png'),
	ic_back: require('./images/ic_back.png'),
	logo_spro: require('./images/logo_spro.png'),
	background_onboard: require('./images/background_onboard.png'),
	background_login: require('./images/background_login.png'),
	ic_eye: require('./images/ic_eye.png'),
	ic_eye_slash: require('./images/ic_eye_slash.png'),
	ic_arrow_down_vector: require('./images/ic_arrow_down_vector.png'),
	ic_finish: require('./images/ic_finish.png'),
	ic_overrated: require('./images/ic_overrated.png'),
	ic_waiting: require('./images/ic_waiting.png'),
	ic_reopen: require('./images/ic_reopen.png'),
	ic_issue: require('./images/ic_Issue.png'),
	ic_Feedback: require('./images/ic_Feedback.png'),
	ic_CancelTask: require('./images/ic_CancelTask.png'),
	ic_Assign: require('./images/ic_Assign.png'),
	ic_Running: require('./images/ic_Running.png'),
	ic_ShareTask: require('./images/ic_ShareTask.png'),
	ic_search: require('./images/ic_search.png'),
	ic_camera_avatar: require('./images/ic_camera_avatar.png'),
	ic_more: require('./images/ic_more.png'),
	ic_more_selected: require('./images/ic_more_selected.png'),
	ic_avatar: require('./images/ic_avatar.png'),
	ic_next: require('./images/ic_next.png'),
	ic_setting: require('./images/ic_setting.png'),
	ic_logout: require('./images/ic_logout.png'),
};
